os: linux
dist: trusty
group: stable
language: node_js
script: "npm test && npm run lint"
node_js: "node"
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
branches:
  except:
  - l10n_dev
