os: linux
dist: trusty
group: stable
language: node_js
script: "cp src/config.example.yml src/config.yml&& npm test && npm run lint"
node_js: "10.12.0"
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
branches:
  except:
  - l10n_dev
